name: CI

on:
  pull_request:
    branches:
    - dev
    - stg
    - prd

env:
  targetBranch: ${{ github.event.pull_request.base.ref }}
  stgRole: arn:aws:iam::851725514822:role/GitHub_Actions
  prdRole: arn:aws:iam::590183972824:role/GitHub_Actions

jobs:

  path-filter:
    name: Setup Path Filter
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      terraform: ${{ steps.filter.outputs.terraform }}
    steps:
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: | # purposefully exclude README and LICENSE
          terraform:
            - 'terraform/**'

  terraform-plan:
    name: 'Terraform Plan'
    needs: [path-filter]
    if: ${{ needs.path-filter.outputs.terraform == 'true'}}
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:

    # configure credentials
    - name: Configure AWS Credentials (stg)
      env:
        workingDirectory: ./terraform/stg
      if: ${{ env.targetBranch == 'dev' || env.targetBranch == 'stg' }}
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-west-1
        role-to-assume: ${{ env.stgRole }}
        role-session-name: gha-session

    - name: Configure AWS Credentials (prd)
      env:
        workingDirectory: ./terraform/prd
      if: ${{ env.targetBranch == 'prd' }}
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-west-1
        role-to-assume: ${{ env.prdRole }}
        role-session-name: gha-session

    # checkout the repo
    - name: Checkout
      uses: actions/checkout@v4

    # install terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    # run terraform
    - name: Terraform Init
      working-directory: ${{ env.workingDirectory }}
      run: |
        echo ${{ env.targetBranch }}
        terraform init

    - name: Terraform Format
      working-directory: ${{ env.workingDirectory }}
      run: |
        echo ${{ env.workingDirectory }}
        terraform fmt -recursive -check

    - name: Terraform Plan
      working-directory: ${{ env.workingDirectory }}
      run: |
        env
        terraform plan
