name: CI

on:
  pull_request:
    branches:
    - main

jobs:

  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      terraform: ${{ steps.filter.outputs.terraform }}
    steps:
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: | # purposefully exclude README and LICENSE
          terraform:
            - 'main.tf'

  terraform-plan:
    name: 'Terraform Plan'
    needs: [changes]
    if: ${{ needs.changes.outputs.terraform == 'true'}}
    runs-on: ubuntu-latest

    steps:

    # configure credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-west-1
        role-to-assume: arn:aws:iam::211125428779:role/GitHub_Actions
        role-session-name: gha-session

    # checkout the repo
    - name: Checkout
      uses: actions/checkout@v4

    # install terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    # run terraform
    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -recursive -check

    - name: Terraform Plan
      run: terraform plan
