name: CI

on:
  pull_request:
    branches:
    - main

permissions:
  id-token: write
  contents: read # not sure I need this
  pull-requests: read

jobs:

  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    steps:
    - uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: | # purposefully exclude README and License
          top-level-directory:
            - '.github/**'
            - '.terraform/**'
            - '.gitignore'
            - 'main.tf'

    # configure credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-west-1
        role-to-assume: arn:aws:iam::211125428779:role/GitHub_Actions
        role-session-name: gha-session

    # checkout the repo
    - name: Checkout
      uses: actions/checkout@v4

    # install terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    - if: steps.changes.outputs.top-level-directory == 'true'
      name: Terraform
      run: |
        terraform init
        terraform fmt -recursive -check
        terraform plan

